### ISSUE TITLE
Can't get notes

### ISSUE THREAD

**Issue by deadman36g** [sickmartian/quick_simplenote#18]
After I install this and enter my username and password for SimpleNote it forever says downloading note list at the bottom of ST3

I am using Sublime Text 3 Build 3095

**Comment by sickmartian** [comment]
Maybe the username and password is wrong or you can't reach the server?
Try checking the username and password, and also pinging simple-note.appspot.com

If everything is working properly, you can check if the note_cache file exists on the package folder: from the command palette -> browse packages -> QuickSimplenote. If so, you can remove it and try opening sublime again.

If none of that helps I will try to reproduce it using the same version you use, so I would need the platform you are running sublime from, besides the build you already sent. Also, if this is a clear installation, or if you are updating. It should be fixed, but the note_cache is known to get corrupted if it's getting written while sublime updates, so it might help to know it as well.

**Comment by deadman36g** [comment]
So sorry, sickmartian 

I was using an actual username instead of my email for the username part (it has been a long time since I accessed my simplenote account)

Everything is working great now, thank you for your timely response and awesome extension.
