### ISSUE TITLE
Stuck on 'please configure username / password'

### ISSUE THREAD

**Issue by verwinv** [sickmartian/quick_simplenote#21]
Hi, after filling out credentials in _quick_simplenote.sublime-settings_ and saving, the status bar keeps saying `please configure username / password, Line 1, Column 1`. Any idea what I could do to solve? Much thanks.

**Comment by sickmartian** [comment]
Hi, did you try restarting sublime text? Which platform are you using?
Which ST version?

**Comment by verwinv** [comment]
Sorry sorry sorry - just restarted and it works like a charm.

**Comment by sickmartian** [comment]
No problem at all, it's not supposed to get stuck there and need a restart after all
