### ISSUE TITLE
Quick SImplenote won't connect anymore (it was)

### ISSUE THREAD

**Issue by stervel** [sickmartian/quick_simplenote#24]
Per a few days back before this issue posted (I forgot, I thought it was some connection problem at first), it won't connect to the net at all. I previously logged in and everything's fine, until I tap the win+shift+SS and the dialog won't come. Checked the firewall, and everything's okay. Tried to reinstall the package and the ST3 itself but no avail.

What problem it could be?

**Comment by sickmartian** [comment]
Hi stervel,

I would need some additional info to help here:
- Platform you are using
- Console log after you open ST3 (view/show console)

Also, you can try logging into simplenote via the web or another app to check if your credentials are working and trying to open the menu via the command palette (win+shift+P IIRC) looking for quicksimplenote there.

**Comment by stervel** [comment]
Whoops, suddenly it works. Strange.

Well at least TIL about `console` and it explains anything happened in the background. I'm no coder so yea that's a bit new for me.

No problem then, thanks tho.
